# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='Response.proto',
    package='proto.response',
    syntax='proto3',
    serialized_options=b'H\001',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0eResponse.proto\x12\x0eproto.response\"\x92\x02\n\x0cResponsePOJO\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.proto.response.ResponsePOJO.Type\x12(\n\x07message\x18\x02 \x03(\x0b\x32\x17.proto.response.Message\x12+\n\x06result\x18\x03 \x01(\x0b\x32\x16.proto.response.ResultH\x00\x88\x01\x01\x12\x30\n\x0b\x63hannelInfo\x18\x04 \x03(\x0b\x32\x1b.proto.response.ChannelInfo\x12\x12\n\nmemberNick\x18\x05 \x03(\t\")\n\x04Type\x12\n\n\x06RESULT\x10\x00\x12\x0b\n\x07MESSAGE\x10\x01\x12\x08\n\x04INFO\x10\x02\x42\t\n\x07_result\"%\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"=\n\x07Message\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x10\n\x08\x66romNick\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"@\n\x0b\x43hannelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08isPublic\x18\x02 \x01(\x08\x12\x11\n\tmemberNum\x18\x03 \x01(\x05\x42\x02H\x01\x62\x06proto3'
)

_RESPONSEPOJO_TYPE = _descriptor.EnumDescriptor(
    name='Type',
    full_name='proto.response.ResponsePOJO.Type',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='RESULT', index=0, number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='MESSAGE', index=1, number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='INFO', index=2, number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=257,
    serialized_end=298,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEPOJO_TYPE)

_RESPONSEPOJO = _descriptor.Descriptor(
    name='ResponsePOJO',
    full_name='proto.response.ResponsePOJO',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='proto.response.ResponsePOJO.type', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='message', full_name='proto.response.ResponsePOJO.message', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='result', full_name='proto.response.ResponsePOJO.result', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='channelInfo', full_name='proto.response.ResponsePOJO.channelInfo', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='memberNick', full_name='proto.response.ResponsePOJO.memberNick', index=4,
            number=5, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _RESPONSEPOJO_TYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='_result', full_name='proto.response.ResponsePOJO._result',
            index=0, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
    ],
    serialized_start=35,
    serialized_end=309,
)

_RESULT = _descriptor.Descriptor(
    name='Result',
    full_name='proto.response.Result',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='proto.response.Result.result', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='msg', full_name='proto.response.Result.msg', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=311,
    serialized_end=348,
)

_MESSAGE = _descriptor.Descriptor(
    name='Message',
    full_name='proto.response.Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='channel', full_name='proto.response.Message.channel', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='fromNick', full_name='proto.response.Message.fromNick', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='content', full_name='proto.response.Message.content', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=350,
    serialized_end=411,
)

_CHANNELINFO = _descriptor.Descriptor(
    name='ChannelInfo',
    full_name='proto.response.ChannelInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='proto.response.ChannelInfo.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='isPublic', full_name='proto.response.ChannelInfo.isPublic', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='memberNum', full_name='proto.response.ChannelInfo.memberNum', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=413,
    serialized_end=477,
)

_RESPONSEPOJO.fields_by_name['type'].enum_type = _RESPONSEPOJO_TYPE
_RESPONSEPOJO.fields_by_name['message'].message_type = _MESSAGE
_RESPONSEPOJO.fields_by_name['result'].message_type = _RESULT
_RESPONSEPOJO.fields_by_name['channelInfo'].message_type = _CHANNELINFO
_RESPONSEPOJO_TYPE.containing_type = _RESPONSEPOJO
_RESPONSEPOJO.oneofs_by_name['_result'].fields.append(
    _RESPONSEPOJO.fields_by_name['result'])
_RESPONSEPOJO.fields_by_name['result'].containing_oneof = _RESPONSEPOJO.oneofs_by_name['_result']
DESCRIPTOR.message_types_by_name['ResponsePOJO'] = _RESPONSEPOJO
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ChannelInfo'] = _CHANNELINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponsePOJO = _reflection.GeneratedProtocolMessageType('ResponsePOJO', (_message.Message,), {
    'DESCRIPTOR': _RESPONSEPOJO,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.ResponsePOJO)
})
_sym_db.RegisterMessage(ResponsePOJO)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR': _RESULT,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.Result)
})
_sym_db.RegisterMessage(Result)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR': _MESSAGE,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.Message)
})
_sym_db.RegisterMessage(Message)

ChannelInfo = _reflection.GeneratedProtocolMessageType('ChannelInfo', (_message.Message,), {
    'DESCRIPTOR': _CHANNELINFO,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.ChannelInfo)
})
_sym_db.RegisterMessage(ChannelInfo)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
