# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rRequest.proto\x12\rproto.request\"\xec\x02\n\x0bRequestPOJO\x12\x37\n\toperation\x18\x01 \x01(\x0e\x32$.proto.request.RequestPOJO.Operation\x12,\n\x07message\x18\x02 \x01(\x0b\x32\x16.proto.request.MessageH\x00\x88\x01\x01\x12,\n\x07\x63hannel\x18\x03 \x01(\x0b\x32\x16.proto.request.ChannelH\x01\x88\x01\x01\"\xaf\x01\n\tOperation\x12\n\n\x06RETAIN\x10\x00\x12\n\n\x06LOGOUT\x10\x01\x12\x0c\n\x08JOIN_CHA\x10\x02\x12\x0c\n\x08QUIT_CHA\x10\x03\x12\x0e\n\nCREATE_CHA\x10\x04\x12\x0b\n\x07SENDMSG\x10\x05\x12\n\n\x06GETMSG\x10\x06\x12\r\n\tHEARTBEAT\x10\x07\x12\x0b\n\x07VERSION\x10\x08\x12\x14\n\x10GET_CHANNEL_LIST\x10\t\x12\x13\n\x0fGET_MEMBER_LIST\x10\nB\n\n\x08_messageB\n\n\x08_channel\"V\n\x07\x43hannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x13\n\x06ticket\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04nick\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_ticketB\x07\n\x05_nick\"+\n\x07Message\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tB\x02H\x01\x62\x06proto3')

_REQUESTPOJO = DESCRIPTOR.message_types_by_name['RequestPOJO']
_CHANNEL = DESCRIPTOR.message_types_by_name['Channel']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_REQUESTPOJO_OPERATION = _REQUESTPOJO.enum_types_by_name['Operation']
RequestPOJO = _reflection.GeneratedProtocolMessageType('RequestPOJO', (_message.Message,), {
    'DESCRIPTOR': _REQUESTPOJO,
    '__module__': 'Request_pb2'
    # @@protoc_insertion_point(class_scope:proto.request.RequestPOJO)
})
_sym_db.RegisterMessage(RequestPOJO)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
    'DESCRIPTOR': _CHANNEL,
    '__module__': 'Request_pb2'
    # @@protoc_insertion_point(class_scope:proto.request.Channel)
})
_sym_db.RegisterMessage(Channel)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR': _MESSAGE,
    '__module__': 'Request_pb2'
    # @@protoc_insertion_point(class_scope:proto.request.Message)
})
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'H\001'
    _REQUESTPOJO._serialized_start = 33
    _REQUESTPOJO._serialized_end = 397
    _REQUESTPOJO_OPERATION._serialized_start = 198
    _REQUESTPOJO_OPERATION._serialized_end = 373
    _CHANNEL._serialized_start = 399
    _CHANNEL._serialized_end = 485
    _MESSAGE._serialized_start = 487
    _MESSAGE._serialized_end = 530
# @@protoc_insertion_point(module_scope)
