# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eResponse.proto\x12\x0eproto.response\"\xb0\x02\n\x0cResponsePOJO\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.proto.response.ResponsePOJO.Type\x12(\n\x07message\x18\x02 \x03(\x0b\x32\x17.proto.response.Message\x12+\n\x06result\x18\x03 \x01(\x0b\x32\x16.proto.response.ResultH\x00\x88\x01\x01\x12\x30\n\x0b\x63hannelInfo\x18\x04 \x03(\x0b\x32\x1b.proto.response.ChannelInfo\x12\x12\n\nmemberNick\x18\x05 \x03(\t\"G\n\x04Type\x12\n\n\x06RESULT\x10\x00\x12\x0b\n\x07MESSAGE\x10\x01\x12\x0f\n\x0b\x43hannelList\x10\x02\x12\x15\n\x11\x43hannelMemberList\x10\x03\x42\t\n\x07_result\"%\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"N\n\x07Message\x12\x0f\n\x07recTime\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x10\n\x08\x66romNick\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"@\n\x0b\x43hannelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08isPublic\x18\x02 \x01(\x08\x12\x11\n\tmemberNum\x18\x03 \x01(\x05\x42\x02H\x01\x62\x06proto3')

_RESPONSEPOJO = DESCRIPTOR.message_types_by_name['ResponsePOJO']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_CHANNELINFO = DESCRIPTOR.message_types_by_name['ChannelInfo']
_RESPONSEPOJO_TYPE = _RESPONSEPOJO.enum_types_by_name['Type']
ResponsePOJO = _reflection.GeneratedProtocolMessageType('ResponsePOJO', (_message.Message,), {
    'DESCRIPTOR': _RESPONSEPOJO,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.ResponsePOJO)
})
_sym_db.RegisterMessage(ResponsePOJO)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR': _RESULT,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.Result)
})
_sym_db.RegisterMessage(Result)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR': _MESSAGE,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.Message)
})
_sym_db.RegisterMessage(Message)

ChannelInfo = _reflection.GeneratedProtocolMessageType('ChannelInfo', (_message.Message,), {
    'DESCRIPTOR': _CHANNELINFO,
    '__module__': 'Response_pb2'
    # @@protoc_insertion_point(class_scope:proto.response.ChannelInfo)
})
_sym_db.RegisterMessage(ChannelInfo)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'H\001'
    _RESPONSEPOJO._serialized_start = 35
    _RESPONSEPOJO._serialized_end = 339
    _RESPONSEPOJO_TYPE._serialized_start = 257
    _RESPONSEPOJO_TYPE._serialized_end = 328
    _RESULT._serialized_start = 341
    _RESULT._serialized_end = 378
    _MESSAGE._serialized_start = 380
    _MESSAGE._serialized_end = 458
    _CHANNELINFO._serialized_start = 460
    _CHANNELINFO._serialized_end = 524
# @@protoc_insertion_point(module_scope)
